title: Carlos
logo: me.png
description: Production Reliability, Cyber Security & Private Cloud Infrastructure
show_downloads: false

url: "https://sfd-markets.github.io"
baseurl: "/cv"

navigation:
  - title: Resume
    url: /
  - title: Projects
    url: /portfolio/

theme: jekyll-theme-minimal
email: carlos@sfdmarkets.com

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

whitelist:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: portfolio
    values:
      layout: default
